# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3369e85940d8b17e7adc6b20e76ed6166005095888a39299a6888d3699fa2ae2249ef16beacdb933032a566df2ae03a29b2c45501db5287884d6275b10d4aedf

test:
  secret_key_base: cff2b7a3f5c57f85116524b0190034ae73b05057685cfa239f723d78e91e5a1f38b392cc66abfcc9abe02f62fe564b74a366ee6f41aa65401aaa351cb3474b97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
